### PR TITLE
Use environment-based Docker image in Docker-compose

### PR DESCRIPTION
**Pull request by jnsereko**
The idea here is to use Hashicorp Vault and direnv to automate env secrets.   

The ideology is simple
- Install and setup [Hashicorp Vault](https://developer.hashicorp.com/vault/install) and [direnv](https://direnv.net/docs/installation.html)  locally  
- go to the home directory of this repo and run `direnv allow .` ( otherwise direnv will not load the env files)
- we shall have a simple private script to run once, which will set secrete data ie, database user, password, name etc
- we first load the secrets in the envrc using direnv
- run `direnv source_env .env.dev` for `dev` environment or `direnv source_env .env.qa` for the `qa` environment 
- finally do our usual `docker compose up`

I am open for further discussion on this 
cc @michaelbontyes

### CODE REVIEW

**Comment by sherrif10** [comment]
You got failures on this repo @jnsereko

**Comment by jnsereko** [comment]
> You got failures on this repo @jnsereko

Upload Configuration Artifact should fail. Looking into `Build and Validate Configuration`

**Comment by jnsereko** [comment]
closing this because i have a better approach
I will reopen when this approach turns out better

**Comment by jnsereko** [comment]
uncertified logic in this is when we have different secretes for both `qa` and `dev`

Solution:
Creating different variables for secretes ie having `QA_OPENMRS_DB_USER` and `DEV_OPENMRS_DB_USER` and dynamically loading these variable in the docker compose file

**Comment by sherrif10** [comment]
Makes sense, In that case you can manage different configs for different variables.

**Pull request closed without merging**
